SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_RADIUS = 20
PLAYER_ACCELERATION_MULTIPLIER = 2
PLAYER_ACCELERATION_AMOUNT = 3
PLAYER_DEACCELERATION_AMOUNT = 4
LINE_WIDTH = 2
