SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_TURN_SPEED = 290
PLAYER_SPEED = 150
PLAYER_RADIUS = 20
PLAYER_ACCELERATION_MULTIPLIER = 2
PLAYER_ACCELERATION_AMOUNT = 3
PLAYER_DEACCELERATION_AMOUNT = 4
LINE_WIDTH = 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
